import * as S from '@fp-ts/schema'

export const Roast = S.struct({
  beanChargeTemperature: S.number,
  beanDropTemperature: S.number,
  drumChargeTemperature: S.number,
  drumDropTemperature: S.number,
  beanTemperature: S.array(S.number),
  drumTemperature: S.array(S.number),
  beanDerivative: S.array(S.number),
  ibtsDerivative: S.array(S.number),
  exitTemperature: S.array(S.number),
  preheatTemperature: S.number,
  roastStartIndex: S.number,
  roastEndIndex: S.number,
  totalRoastTime: S.number,
  indexFirstCrackStart: S.number,
  indexFirstCrackEnd: S.number,
  indexSecondCrackStart: S.number,
  indexSecondCrackEnd: S.number,
  indexYellowingStart: S.number,
  weightGreen: S.string,
  weightRoasted: S.string,
  roastNumber: S.number,
  sampleRate: S.number,
  serialNumber: S.number,
  hardware: S.number,
  IRSensor: S.number,
  firmware: S.number,
  actions: S.struct({
    actionTempList: S.array(S.unknown),
    actionTimeList: S.array(
      S.struct({
        ctrlType: S.number,
        index: S.number,
        value: S.number,
      })
    ),
  }),
  missingSeconds: S.array(S.unknown),
  rorPreheat: S.number,
  uid: S.string,
  userId: S.string,
  dateTime: S.number,
  softwareVersion: S.string,
  firmwareVersion: S.number,
  roastName: S.string,
  ambient: S.number,
  humidity: S.number,
  beanId: S.string,
  updatedAt: S.number,
  roastDegree: S.number,
  guid: S.string,
  isPrivate: S.number,
})
